import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gradient-to-r from-rgb-background-start to-rgb-background-end p-4">
          <div className="container mx-auto">
            <h1 className="text-2xl text-rgb-foreground font-semibold">
              Meu Aplicativo
            </h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
